"""empty message

Revision ID: 02d12f05b556
Revises: 19a1445ef7fc
Create Date: 2026-01-29 16:44:36.549468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d12f05b556'
down_revision: Union[str, Sequence[str], None] = '19a1445ef7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('roll_no'), table_name='students')
    op.create_index(op.f('ix_students_roll_no'), 'students', ['roll_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_roll_no'), table_name='students')
    op.create_index(op.f('roll_no'), 'students', ['roll_no'], unique=True)
    # ### end Alembic commands ###
