"""password value change

Revision ID: 5e272ed77ad5
Revises: 28ccf142fd87
Create Date: 2026-01-29 20:03:42.688008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e272ed77ad5'
down_revision: Union[str, Sequence[str], None] = '28ccf142fd87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('ADMIN', 'STUDENT'),
               type_=sa.Enum('ADMIN', 'USER', name='userrole'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'USER', name='userrole'),
               type_=mysql.ENUM('ADMIN', 'STUDENT'),
               existing_nullable=True)
    # ### end Alembic commands ###
